


database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: big-market-nest
  connectorPackage: mysql2
  synchronize: false
  logging: false
  extra:
    connectionLimit: 10 #根据需要调整连接池大小
    acquireTimeout: 10000 #获取连接的超时时间
    waitForConnections: true #当没有连接可用时是否等待
    queueLimit: 0 #排队等待连接的请求数量限制
    idleTimeout: 60000 #空闲连接超时时间（毫秒）
    connectTimeout: 30000 #连接超时时间（毫秒）
  keepConnectionAlive: true
  retryDelay: 3000 #重试间隔时间（毫秒）
  retryAttempts: 10 # 重试次数

redis:
  type: single
  options:
    host: localhost
    port: 6379
    password: 
    db: 0
